//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_BD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLOBAL_INFO
    {
        public int ID_GLOBAL_INFO { get; set; }
        public int CARNAME_ID { get; set; }
        public int WHERE_THE_CAR_COMES_FROM_ID { get; set; }
        public int SUPPLIER_ID { get; set; }
    
        public virtual CAR CAR { private get; set; }
        public virtual SUPPLIER SUPPLIER { private get; set; }
        public virtual WHERE_THE_CAR_COMES_FROM WHERE_THE_CAR_COMES_FROM { private get; set; }
    }
}
