//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_BD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHERE_THE_CAR_COMES_FROM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WHERE_THE_CAR_COMES_FROM()
        {
            this.GLOBAL_INFO = new HashSet<GLOBAL_INFO>();
        }
    
        public int ID_WHERE_THE_CAR_COMES_FROM { get; set; }
        public string TITLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLOBAL_INFO> GLOBAL_INFO { get; set; }
    }
}
